const state={className:'My Class',students:[],centers:[],design:'classic',capacityMode:'people-number'};
const storageKey='littleSignsV01';
function save(){localStorage.setItem(storageKey,JSON.stringify(state));}
function restore(){try{const saved=JSON.parse(localStorage.getItem(storageKey));if(saved)Object.assign(state,saved);}catch(e){}syncInputs();renderCenters();renderTags();renderPreviewOptions();applyDesign();renderDesignPreview();updateSummary();}
function syncInputs(){const cn=document.getElementById('className'),sn=document.getElementById('studentNames'),cm=document.getElementById('capacityMode');if(cn)cn.value=state.className||'My Class';if(sn)sn.value=(state.students||[]).join('\n');if(cm)cm.value=state.capacityMode||'people-number';}
function go(id){document.querySelectorAll('.screen').forEach(el=>el.classList.remove('active'));document.getElementById(id)?.classList.add('active');document.querySelectorAll('.step').forEach(el=>{el.classList.toggle('active',el.dataset.screen===id);const order=['design','centers','classroom','preview'];el.classList.toggle('done',order.indexOf(el.dataset.screen)<order.indexOf(id));});if(id==='design')renderDesignPreview();if(id==='centers')renderCenters();if(id==='classroom')renderTags();if(id==='preview'){renderPreviewOptions();renderPreview();renderPreviewTags();updateSummary();}window.scrollTo({top:0,behavior:'smooth'});}
document.querySelectorAll('.step').forEach(btn=>btn.addEventListener('click',()=>go(btn.dataset.screen)));
function chooseDesign(name){state.design=name;save();applyDesign();renderDesignPreview();updateSummary();}
function applyDesign(){document.body.dataset.design=state.design||'classic';document.querySelectorAll('.design-card').forEach(x=>x.classList.toggle('selected',x.dataset.design===state.design));}
function setCapacityMode(v){state.capacityMode=v;save();renderDesignPreview();renderPreview();}
function captureClass(){state.className=document.getElementById('className')?.value.trim()||'My Class';state.students=(document.getElementById('studentNames')?.value||'').split(/\n|,/).map(x=>x.trim()).filter(Boolean);save();renderTags();renderPreviewTags();updateSummary();}
function saveClass(){captureClass();}
function renderTags(){const el=document.getElementById('tagPreview');if(el)el.innerHTML=tagsHtml();}
function renderPreviewTags(){const el=document.getElementById('previewTagList');if(el)el.innerHTML=tagsHtml();}
function tagsHtml(){return state.students.length?state.students.map(name=>`<div class="tag">${escapeHtml(name)}</div>`).join(''):'<div class="empty">Your matching name tags will appear here as you add names.</div>';}
function newId(){return (crypto.randomUUID&&crypto.randomUUID())||String(Date.now()+Math.random());}
function addCenter(name='New Center',capacity=2,icon='⭐'){state.centers.push({id:newId(),name,capacity,icon});save();renderCenters();renderPreviewOptions();}
function quickAdd(name,capacity,icon){if(!state.centers.some(c=>c.name===name))addCenter(name,capacity,icon);}
function removeCenter(id){state.centers=state.centers.filter(c=>c.id!==id);save();renderCenters();renderPreviewOptions();renderPreview();}
function updateCenter(id,key,value){const c=state.centers.find(c=>c.id===id);if(!c)return;c[key]=key==='capacity'?Math.max(1,Math.min(6,Number(value)||1)):value;save();renderPreviewOptions();renderPreview();}
function renderCenters(){const el=document.getElementById('centerList');if(!el)return;if(!state.centers.length){el.innerHTML='<div class="empty">Choose centers above or add a custom center.</div>';return;}el.innerHTML=state.centers.map(c=>`<div class="center-row"><input value="${escapeAttr(c.name)}" onchange="updateCenter('${c.id}','name',this.value)"><select onchange="updateCenter('${c.id}','capacity',this.value)">${Array.from({length:6},(_,i)=>`<option value="${i+1}" ${c.capacity===i+1?'selected':''}>${i+1} friend${i?'s':''}</option>`).join('')}</select><button class="remove" onclick="removeCenter('${c.id}')">×</button></div>`).join('');}
function renderPreviewOptions(){const sel=document.getElementById('previewCenter');if(!sel)return;const current=sel.value;sel.innerHTML=state.centers.map(c=>`<option value="${c.id}">${escapeHtml(c.name)} — ${c.capacity}</option>`).join('');if(state.centers.some(c=>c.id===current))sel.value=current;}
function childOutline(){return `<svg class="person" viewBox="0 0 40 58" aria-hidden="true"><circle cx="20" cy="10" r="7" fill="none" stroke="currentColor" stroke-width="3"/><path d="M20 18v18M11 27l9-7 9 7M14 51l6-15 6 15" fill="none" stroke="currentColor" stroke-width="3" stroke-linecap="round" stroke-linejoin="round"/></svg>`;}
function spotsHtml(cap){const count=Math.min(cap,6),layoutClass=count>=4?'spots two-col':'spots';return `<div class="${layoutClass}">${Array.from({length:count},()=>'<div class="spot">NAME</div>').join('')}</div>`;}
function capacityHtml(c,mode){if(mode==='spots')return '';const p=mode==='people-number'||mode==='people',f=mode==='faces-number'||mode==='faces',n=mode==='people-number'||mode==='faces-number'||mode==='number';return `<div class="capacity">${p?`<div class="people">${Array.from({length:c.capacity},()=>childOutline()).join('')}</div>`:''}${f?`<div class="faces">${Array.from({length:c.capacity},()=>'<span class="face">☺</span>').join('')}</div>`:''}${n?`<div class="number">${c.capacity}</div>`:''}</div>`;}
function signHtml(c,mode=state.capacityMode||'people-number'){return `<div class="sign"><div class="sign-top"><div class="sign-title">${escapeHtml(c.name)}</div><div class="center-visual"><div class="visual-card">${c.icon||'⭐'}</div></div>${capacityHtml(c,mode)}</div><div class="sign-bottom">${spotsHtml(c.capacity)}</div></div>`;}
function renderDesignPreview(){const el=document.getElementById('designPreview');if(!el)return;const sample={name:'Blocks',capacity:4,icon:'🧱'};el.innerHTML=`<div class="sign-wrap sample-sign">${signHtml(sample)}</div>`;}
function renderPreview(){const el=document.getElementById('livePreview');if(!el)return;const id=document.getElementById('previewCenter')?.value,c=state.centers.find(x=>x.id===id)||state.centers[0];if(!c){el.innerHTML='<div class="empty">Add at least one center to preview your set.</div>';return;}el.innerHTML=`<div class="sign-wrap">${signHtml(c)}</div>`;}
function updateSummary(){const names={classic:'Classic Choice',playful:'Playful',minimal:'Simple'};const d=document.getElementById('designSummary'),c=document.getElementById('classSummary');if(d)d.textContent=names[state.design]||'Classic Choice';if(c)c.textContent=`${state.className||'My Class'} • ${state.students.length} student${state.students.length===1?'':'s'}`;}
function tagPrintPage(){const names=state.students.length?state.students:['Sample Name'];return `<div class="print-tags-page"><h2>${escapeHtml(state.className)} — Center Name Tags</h2><p>Print at 100% / Actual Size. Each tag is 3.25 × 1.25 inches.</p><div class="print-tags-grid">${names.map(n=>`<div class="tag">${escapeHtml(n)}</div>`).join('')}</div></div>`;}
function printCurrent(){const c=state.centers.find(x=>x.id===document.getElementById('previewCenter')?.value)||state.centers[0];if(!c)return;document.getElementById('printScreen').innerHTML=`<div class="print-sign-page">${signHtml(c)}</div>`;window.print();}
function printTags(){document.getElementById('printScreen').innerHTML=tagPrintPage();window.print();}
function printCompleteSet(){if(!state.centers.length)return;document.getElementById('printScreen').innerHTML=state.centers.map(c=>`<div class="print-sign-page">${signHtml(c)}</div>`).join('')+tagPrintPage();window.print();}
function loadDemo(){state.className='Demo Class';state.students=['Avery','Eli','Harper','Jordan','Mia','Noah'];state.centers=[{id:'writing',name:'Writing',capacity:2,icon:'✏️'},{id:'blocks',name:'Blocks',capacity:4,icon:'🧱'},{id:'art',name:'Art',capacity:4,icon:'🎨'}];save();syncInputs();renderCenters();renderTags();renderPreviewOptions();go('preview');}
function escapeHtml(s=''){return String(s).replace(/[&<>'\"]/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','\"':'&quot;'}[m]));}function escapeAttr(s=''){return escapeHtml(s);}restore();