const state={className:'My Class',students:[],centers:[]};
const storageKey='littleSignsV01';
function save(){localStorage.setItem(storageKey,JSON.stringify(state));}
function restore(){try{const saved=JSON.parse(localStorage.getItem(storageKey));if(saved)Object.assign(state,saved);}catch(e){}syncInputs();renderCenters();renderTags();renderPreviewOptions();}
function syncInputs(){document.getElementById('className').value=state.className||'My Class';document.getElementById('studentNames').value=(state.students||[]).join('\n');}
function go(id){document.querySelectorAll('.screen').forEach(el=>el.classList.remove('active'));const target=document.getElementById(id);if(target)target.classList.add('active');document.querySelectorAll('.tab').forEach(el=>el.classList.toggle('active',el.dataset.screen===id));if(id==='preview'){renderPreviewOptions();renderPreview();renderPreviewTags();}window.scrollTo({top:0,behavior:'smooth'});}
document.querySelectorAll('.tab').forEach(btn=>btn.addEventListener('click',()=>go(btn.dataset.screen)));
function saveClass(){state.className=document.getElementById('className').value.trim()||'My Class';state.students=document.getElementById('studentNames').value.split(/\n|,/).map(x=>x.trim()).filter(Boolean);save();renderTags();renderPreviewTags();}
function renderTags(){const el=document.getElementById('tagPreview');if(!el)return;el.innerHTML=tagsHtml();}
function renderPreviewTags(){const el=document.getElementById('previewTagList');if(!el)return;el.innerHTML=tagsHtml();}
function tagsHtml(){return state.students.length?state.students.map(name=>`<div class="tag">${escapeHtml(name)}</div>`).join(''):'<div class="empty">Add your class list to see matching tags here.</div>';}
function newId(){return (crypto.randomUUID&&crypto.randomUUID())||String(Date.now()+Math.random());}
function addCenter(name='New Center',capacity=2,icon='⭐'){state.centers.push({id:newId(),name,capacity,icon});save();renderCenters();renderPreviewOptions();}
function quickAdd(name,capacity,icon){if(!state.centers.some(c=>c.name===name))addCenter(name,capacity,icon);}
function removeCenter(id){state.centers=state.centers.filter(c=>c.id!==id);save();renderCenters();renderPreviewOptions();renderPreview();}
function updateCenter(id,key,value){const c=state.centers.find(c=>c.id===id);if(!c)return;c[key]=key==='capacity'?Math.max(1,Math.min(6,Number(value)||1)):value;save();renderPreviewOptions();renderPreview();}
function renderCenters(){const el=document.getElementById('centerList');if(!el)return;if(!state.centers.length){el.innerHTML='<div class="empty">No centers yet. Tap one of the quick-add buttons above.</div>';return;}el.innerHTML=state.centers.map(c=>`<div class="center-row"><input value="${escapeAttr(c.name)}" onchange="updateCenter('${c.id}','name',this.value)"/><select onchange="updateCenter('${c.id}','capacity',this.value)">${Array.from({length:6},(_,i)=>`<option value="${i+1}" ${c.capacity===i+1?'selected':''}>${i+1} friend${i?'s':''}</option>`).join('')}</select><button class="remove" onclick="removeCenter('${c.id}')">×</button></div>`).join('');}
function renderPreviewOptions(){const sel=document.getElementById('previewCenter');if(!sel)return;const current=sel.value;sel.innerHTML=state.centers.map(c=>`<option value="${c.id}">${escapeHtml(c.name)} — ${c.capacity}</option>`).join('');if(state.centers.some(c=>c.id===current))sel.value=current;}
function childOutline(){return `<svg class="person" viewBox="0 0 40 58" aria-hidden="true"><circle cx="20" cy="10" r="7" fill="none" stroke="currentColor" stroke-width="3"/><path d="M20 18v18M11 27l9-7 9 7M14 51l6-15 6 15" fill="none" stroke="currentColor" stroke-width="3" stroke-linecap="round" stroke-linejoin="round"/></svg>`;}
function spotsHtml(cap){const count=Math.min(cap,6);const layoutClass=count>=4?'spots two-col':'spots';return `<div class="${layoutClass}">${Array.from({length:count},()=>'<div class="spot">NAME</div>').join('')}</div>`;}
function capacityHtml(c,mode){if(mode==='spots')return '';const showPeople=mode==='people-number'||mode==='people';const showFaces=mode==='faces-number'||mode==='faces';const showNumber=mode==='people-number'||mode==='faces-number'||mode==='number';return `<div class="capacity">${showPeople?`<div class="people">${Array.from({length:c.capacity},()=>childOutline()).join('')}</div>`:''}${showFaces?`<div class="faces">${Array.from({length:c.capacity},()=>'<span class="face">☺</span>').join('')}</div>`:''}${showNumber?`<div class="number">${c.capacity}</div>`:''}</div>`;}
function signHtml(c,mode='people-number'){return `<div class="sign"><div class="sign-top"><div class="sign-title">${escapeHtml(c.name)}</div><div class="center-visual"><div class="visual-card">${c.icon||'⭐'}</div></div>${capacityHtml(c,mode)}</div><div class="sign-bottom">${spotsHtml(c.capacity)}</div></div>`;}
function renderPreview(){const el=document.getElementById('livePreview');if(!el)return;const sel=document.getElementById('previewCenter');const id=sel?sel.value:'';const c=state.centers.find(x=>x.id===id)||state.centers[0];if(!c){el.innerHTML='<div class="empty">Add a center first.</div>';return;}const mode=document.getElementById('capacityMode')?.value||'people-number';el.innerHTML=`<div class="sign-wrap">${signHtml(c,mode)}</div>`;}
function tagPrintPage(){const names=state.students.length?state.students:['Sample Name'];return `<div class="print-tags-page"><h2>${escapeHtml(state.className)} — Center Name Tags</h2><p>Print at 100% / Actual Size. Each tag is 3.25 × 1.25 inches.</p><div class="print-tags-grid">${names.map(n=>`<div class="tag">${escapeHtml(n)}</div>`).join('')}</div></div>`;}
function printCurrent(){const c=state.centers.find(x=>x.id===document.getElementById('previewCenter')?.value)||state.centers[0];if(!c)return;const mode=document.getElementById('capacityMode')?.value||'people-number';document.getElementById('printScreen').innerHTML=`<div class="print-sign-page">${signHtml(c,mode)}</div>`;window.print();}
function printTags(){document.getElementById('printScreen').innerHTML=tagPrintPage();window.print();}
function printCompleteSet(){if(!state.centers.length)return;const mode=document.getElementById('capacityMode')?.value||'people-number';const signs=state.centers.map(c=>`<div class="print-sign-page">${signHtml(c,mode)}</div>`).join('');document.getElementById('printScreen').innerHTML=signs+tagPrintPage();window.print();}
function loadDemo(){state.className='Demo Class';state.students=['Avery','Eli','Harper','Jordan','Mia','Noah'];state.centers=[{id:'writing',name:'Writing',capacity:2,icon:'✏️'},{id:'blocks',name:'Blocks',capacity:4,icon:'🧱'},{id:'art',name:'Art',capacity:4,icon:'🎨'},{id:'library',name:'Library',capacity:3,icon:'📚'},{id:'science',name:'Science',capacity:4,icon:'🔎'},{id:'dramatic',name:'Dramatic Play',capacity:5,icon:'🏠'}];save();syncInputs();renderCenters();renderTags();renderPreviewOptions();go('preview');}
function escapeHtml(s=''){return String(s).replace(/[&<>'\"]/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','\"':'&quot;'}[m]));}
function escapeAttr(s=''){return escapeHtml(s);}
restore();