const state={className:'My Class',students:[],centers:[],design:'modern-boho',capacityMode:'people-number',tagStyle:'theme'};const storageKey='littleSignsV01';
const PAGE_W_IN=8.5,PAGE_H_IN=11,TAG_W_IN=3.5;
const MODERN_BOHO_LAYOUT={centerArtTopIn:1.90,centerArtLeftIn:1.00,capacityLeftIn:5.65,tagSetTopIn:5.25};
const assets={bohoBackground:'themes/modern-boho/Boho%20sign%20background.png',bohoFineMotor:'themes/modern-boho/centers/boho%20sign%20fine%20motor.png',childSilhouette:'themes/modern-boho/sign%20child%20silhouette.png',bohoNameTag:'themes/modern-boho/boho%20nametag.png'};
function save(){localStorage.setItem(storageKey,JSON.stringify(state));}
function restore(){try{const saved=JSON.parse(localStorage.getItem(storageKey));if(saved){state.className=saved.className||state.className;state.students=Array.isArray(saved.students)?saved.students:state.students;state.centers=Array.isArray(saved.centers)?saved.centers:state.centers;state.design=saved.design||state.design;state.capacityMode=saved.capacityMode||state.capacityMode;state.tagStyle=saved.tagStyle||state.tagStyle;}}catch(e){}if(state.design==='classic')state.design='modern-boho';if(!state.tagStyle)state.tagStyle='theme';syncInputs();renderCenters();renderTags();renderPreviewOptions();applyDesign();renderDesignPreview();updateSummary();loadTagRatio();}
function syncInputs(){const cn=document.getElementById('className'),sn=document.getElementById('studentNames'),cm=document.getElementById('capacityMode'),ts=document.getElementById('tagStyle');if(cn)cn.value=state.className||'My Class';if(sn)sn.value=(state.students||[]).join('\n');if(cm)cm.value=state.capacityMode||'people-number';if(ts)ts.value=state.tagStyle||'theme';}
function pctY(inches){return (Number(inches)/PAGE_H_IN*100).toFixed(4)+'%';}function pctX(inches){return (Number(inches)/PAGE_W_IN*100).toFixed(4)+'%';}
function loadTagRatio(){const img=new Image();img.onload=()=>{if(img.naturalWidth&&img.naturalHeight){document.documentElement.style.setProperty('--boho-tag-ratio',`${img.naturalWidth}/${img.naturalHeight}`);renderDesignPreview();renderTags();renderPreviewTags();renderPreview();}};img.src=assets.bohoNameTag;}
function go(id){document.querySelectorAll('.screen').forEach(el=>el.classList.remove('active'));document.getElementById(id)?.classList.add('active');document.querySelectorAll('.step').forEach(el=>{el.classList.toggle('active',el.dataset.screen===id);const order=['design','centers','classroom','preview'];el.classList.toggle('done',order.indexOf(el.dataset.screen)<order.indexOf(id));});if(id==='design'){syncInputs();renderDesignPreview();}if(id==='centers')renderCenters();if(id==='classroom')renderTags();if(id==='preview'){renderPreviewOptions();renderPreview();renderPreviewTags();updateSummary();}window.scrollTo({top:0,behavior:'smooth'});}document.querySelectorAll('.step').forEach(btn=>btn.addEventListener('click',()=>go(btn.dataset.screen)));
function chooseDesign(name){state.design=name;save();applyDesign();renderDesignPreview();updateSummary();}function applyDesign(){document.body.dataset.design=state.design||'modern-boho';document.querySelectorAll('.design-card').forEach(x=>x.classList.toggle('selected',x.dataset.design===state.design));}function setCapacityMode(v){state.capacityMode=v;save();renderDesignPreview();renderPreview();}function setTagStyle(v){state.tagStyle=v;save();renderTags();renderPreviewTags();renderDesignPreview();renderPreview();}
function captureClass(){state.className=document.getElementById('className')?.value.trim()||'My Class';state.students=(document.getElementById('studentNames')?.value||'').split(/\n|,/).map(x=>x.trim()).filter(Boolean);save();renderTags();renderPreviewTags();updateSummary();}function saveClass(){captureClass();}
function initials(name=''){const parts=String(name).trim().split(/\s+/).filter(Boolean);if(!parts.length)return '';return (parts[0][0]+(parts[1]?.[0]||'')).toUpperCase();}
function tagInner(name=''){const safe=escapeHtml(name);if(state.tagStyle==='blank')return '';if(state.tagStyle==='initial')return `<span class="tag-initial">${escapeHtml(initials(name))}</span><span class="tag-name">${safe}</span>`;if(state.tagStyle==='name')return `<span class="tag-name only">${safe}</span>`;return `<span class="tag-name">${safe}</span>`;}
function tagClass(){return `tag tag-style-${state.tagStyle||'theme'}${state.design==='modern-boho'?' boho-tag':''}`;}
function tagsHtml(){return state.students.length?state.students.map(name=>`<div class="${tagClass()}">${tagInner(name)}</div>`).join(''):'<div class="empty">Your matching name tags will appear here as you add names.</div>';}
function renderTags(){const el=document.getElementById('tagPreview');if(el)el.innerHTML=tagsHtml();}function renderPreviewTags(){const el=document.getElementById('previewTagList');if(el)el.innerHTML=tagsHtml();}
function newId(){return (crypto.randomUUID&&crypto.randomUUID())||String(Date.now()+Math.random());}function addCenter(name='New Center',capacity=2,icon='⭐'){state.centers.push({id:newId(),name,capacity,icon});save();renderCenters();renderPreviewOptions();}function quickAdd(name,capacity,icon){if(!state.centers.some(c=>c.name===name))addCenter(name,capacity,icon);}function removeCenter(id){state.centers=state.centers.filter(c=>c.id!==id);save();renderCenters();renderPreviewOptions();renderPreview();}function updateCenter(id,key,value){const c=state.centers.find(c=>c.id===id);if(!c)return;c[key]=key==='capacity'?Math.max(1,Math.min(6,Number(value)||1)):value;save();renderPreviewOptions();renderPreview();}
function renderCenters(){const el=document.getElementById('centerList');if(!el)return;if(!state.centers.length){el.innerHTML='<div class="empty">Choose centers above or add a custom center.</div>';return;}el.innerHTML=state.centers.map(c=>`<div class="center-row"><input value="${escapeAttr(c.name)}" onchange="updateCenter('${c.id}','name',this.value)"><select onchange="updateCenter('${c.id}','capacity',this.value)">${Array.from({length:6},(_,i)=>`<option value="${i+1}" ${c.capacity===i+1?'selected':''}>${i+1} friend${i?'s':''}</option>`).join('')}</select><button class="remove" onclick="removeCenter('${c.id}')">×</button></div>`).join('');}function renderPreviewOptions(){const sel=document.getElementById('previewCenter');if(!sel)return;const current=sel.value;sel.innerHTML=state.centers.map(c=>`<option value="${c.id}">${escapeHtml(c.name)} — ${c.capacity}</option>`).join('');if(state.centers.some(c=>c.id===current))sel.value=current;}
function childFigure(){return `<img class="person person-image" src="${assets.childSilhouette}" alt="">`;}function spotsHtml(cap){const count=Math.min(cap,6),layoutClass=count>=4?'spots two-col':'spots';return `<div class="${layoutClass}">${Array.from({length:count},()=>'<div class="spot empty-tag-spot" aria-label="Empty name tag space"></div>').join('')}</div>`;}function capacityHtml(c,mode){if(mode==='spots')return '';const p=mode==='people-number'||mode==='people',n=mode==='people-number'||mode==='number';return `<div class="capacity">${p?`<div class="people">${Array.from({length:c.capacity},()=>childFigure()).join('')}</div>`:''}${n?`<div class="number">${c.capacity}</div>`:''}</div>`;}
function isFineMotor(c){return String(c.name||'').toLowerCase().replace(/[^a-z]/g,'').includes('finemotor');}function centerVisual(c){if(state.design==='modern-boho'&&isFineMotor(c))return `<img class="center-art" src="${assets.bohoFineMotor}" alt="Fine Motor center artwork">`;return `<div class="visual-card">${c.icon||'⭐'}</div>`;}
function signHtml(c,mode=state.capacityMode||'people-number'){const boho=state.design==='modern-boho'?' modern-boho-sign':'';const vars=state.design==='modern-boho'?` style="--center-art-top:${pctY(MODERN_BOHO_LAYOUT.centerArtTopIn)};--center-art-left:${pctX(MODERN_BOHO_LAYOUT.centerArtLeftIn)};--capacity-left:${pctX(MODERN_BOHO_LAYOUT.capacityLeftIn)};--tag-set-top:${pctY(MODERN_BOHO_LAYOUT.tagSetTopIn)};--tag-width:${pctX(TAG_W_IN)}"`:'';return `<div class="sign${boho}"${vars}><div class="sign-top"><div class="sign-title">${escapeHtml(c.name)}</div><div class="center-visual">${centerVisual(c)}</div>${capacityHtml(c,mode)}</div><div class="sign-bottom">${spotsHtml(c.capacity)}</div></div>`;}
function renderDesignPreview(){const el=document.getElementById('designPreview');if(!el)return;const sample={name:'Fine Motor',capacity:3,icon:'🧩'};el.innerHTML=`<div class="sign-wrap sample-sign">${signHtml(sample,state.capacityMode||'people-number')}</div>`;}function renderPreview(){const el=document.getElementById('livePreview');if(!el)return;const id=document.getElementById('previewCenter')?.value,c=state.centers.find(x=>x.id===id)||state.centers[0];if(!c){el.innerHTML='<div class="empty">Add at least one center to preview your set.</div>';return;}el.innerHTML=`<div class="sign-wrap">${signHtml(c)}</div>`;}function updateSummary(){const names={'modern-boho':'Modern Boho',playful:'Playful',minimal:'Simple'};const d=document.getElementById('designSummary'),c=document.getElementById('classSummary');if(d)d.textContent=names[state.design]||'Modern Boho';if(c)c.textContent=`${state.className||'My Class'} • ${state.students.length} student${state.students.length===1?'':'s'}`;}
function tagPrintPage(){const names=state.students.length?state.students:['Sample Name'];return `<div class="print-tags-page"><h2>${escapeHtml(state.className)} — Center Name Tags</h2><p>Print at 100% / Actual Size.</p><div class="print-tags-grid">${names.map(n=>`<div class="${tagClass()}">${tagInner(n)}</div>`).join('')}</div></div>`;}function printCurrent(){const c=state.centers.find(x=>x.id===document.getElementById('previewCenter')?.value)||state.centers[0];if(!c)return;document.getElementById('printScreen').innerHTML=`<div class="print-sign-page">${signHtml(c)}</div>`;window.print();}function printTags(){document.getElementById('printScreen').innerHTML=tagPrintPage();window.print();}function printCompleteSet(){if(!state.centers.length)return;document.getElementById('printScreen').innerHTML=state.centers.map(c=>`<div class="print-sign-page">${signHtml(c)}</div>`).join('')+tagPrintPage();window.print();}
function escapeHtml(s=''){return String(s).replace(/[&<>'\"]/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','\"':'&quot;'}[m]));}function escapeAttr(s=''){return escapeHtml(s);}restore();